alter table public.orders
  add column if not exists payment_status text not null default 'pending',
  add column if not exists paid_at timestamptz;

alter table public.orders
  add constraint orders_payment_status_check
  check (payment_status in ('pending', 'paid'));

alter table public.orders
  drop constraint if exists orders_email_status_check;

alter table public.orders
  add constraint orders_email_status_check
  check (email_status in ('pending', 'sending', 'sent', 'failed', 'not_configured'));

create table if not exists public.payment_attempts (
  id bigint generated by default as identity primary key,
  order_id uuid not null references public.orders(id) on delete cascade,
  reference text not null unique,
  amount_kobo integer not null check (amount_kobo > 0),
  currency text not null default 'NGN' check (currency = 'NGN'),
  status text not null default 'pending' check (status in ('pending', 'success', 'failed', 'cancelled', 'abandoned')),
  authorization_url text,
  gateway_transaction_id text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists payment_attempts_order_created_idx
  on public.payment_attempts(order_id, created_at desc);

alter table public.payment_attempts enable row level security;
revoke all on public.payment_attempts from anon, authenticated;
