-- Orders are written only by the FastAPI server after Supabase Auth token verification.
-- RLS is enabled as defense in depth for any future browser-side Data API access.
create table if not exists public.orders (
  id uuid primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  user_email text not null,
  order_number text not null unique,
  customer_name text not null check (char_length(customer_name) between 1 and 100),
  pickup_date date not null,
  notes text not null default '' check (char_length(notes) <= 500),
  subtotal_kobo integer not null check (subtotal_kobo > 0),
  currency text not null default 'NGN' check (currency = 'NGN'),
  email_status text not null default 'pending' check (email_status in ('pending', 'sent', 'failed', 'not_configured')),
  created_at timestamptz not null default now()
);

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id uuid not null references public.orders(id) on delete cascade,
  product_id text not null,
  product_name text not null,
  unit_price_kobo integer not null check (unit_price_kobo > 0),
  quantity integer not null check (quantity between 1 and 25),
  line_total_kobo integer not null check (line_total_kobo = unit_price_kobo * quantity)
);

create index if not exists orders_user_created_idx on public.orders(user_id, created_at desc);
create index if not exists order_items_order_idx on public.order_items(order_id);

alter table public.orders enable row level security;
alter table public.order_items enable row level security;

create policy "Users can read their own orders"
  on public.orders for select to authenticated using ((select auth.uid()) = user_id);

create policy "Users can read their own order items"
  on public.order_items for select to authenticated
  using (exists (
    select 1 from public.orders
    where orders.id = order_items.order_id and orders.user_id = (select auth.uid())
  ));

revoke all on public.orders from anon;
revoke all on public.order_items from anon;
grant select on public.orders, public.order_items to authenticated;
